version: "3"
services: 
    rediska:
        image: "redis"
        ports: 
         - "6379:6379"
    mango:
        image: "mongo"
        ports:
         - "27017:27017"
    controller:
        build: /controller
        ports:
         - "8080:8080"
        network_mode: host
